security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        local:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        activation:
            anonymous: true
            pattern: ^/activation

        main:
            pattern: ^/
            provider: local
            anonymous: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: dashboard_index
                always_use_default_target_path: true
            logout:
                path: logout
                target: /login

    access_control:
        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER